import Control.Exception
import System.IO.Unsafe

main :: IO ()
main = print $ unexceptional $ tail (tail [1])


unexceptional :: a -> Either SomeException a
unexceptional x = unsafePerformIO $ do
    try (return x)











































































































